export const permissionsByRole: Record<string, string[]> = {
  FUNDADOR: ["*"],
  ADMIN: ["*"],
  FINANCEIRO: [
    "dashboard:read",
    "financeiro:read",
    "financeiro:create",
    "financeiro:update",
    "financeiro:delete",
    "contas_pagar:read",
    "contas_pagar:create",
    "contas_pagar:update",
    "contas_pagar:pay",
    "contas_pagar:delete",
    "contas_receber:read",
    "contas_receber:create",
    "contas_receber:update",
    "contas_receber:receive",
    "contas_receber:delete",
    "servicos:read",
    "marketplace:read",
    "fiscal:read",
    "fiscal:create",
    "fiscal:update",
    "relatorios:read",
  ],
  OPERACAO: [
    "dashboard:read",
    "marketplace:read",
    "servicos:read",
    "suporte:read",
    "suporte:create",
    "suporte:update",
    "tarefas:read",
    "tarefas:create",
    "tarefas:update",
    "riscos:read",
    "riscos:create",
  ],
  SUPORTE: [
    "dashboard:read",
    "marketplace:read",
    "suporte:read",
    "suporte:create",
    "suporte:update",
    "tarefas:read",
    "tarefas:create",
  ],
  LEITURA: [
    "dashboard:read",
    "financeiro:read",
    "contas_pagar:read",
    "contas_receber:read",
    "servicos:read",
    "marketplace:read",
    "fornecedores:read",
    "fiscal:read",
    "suporte:read",
    "tarefas:read",
    "riscos:read",
    "riscos:update",
    "riscos:delete",
    "relatorios:read",
  ],
};

export function hasPermission(role: string, permission: string) {
  const permissions = permissionsByRole[role] ?? [];
  return permissions.includes("*") || permissions.includes(permission);
}
